framework:
    cache:
        app: cache.adapter.redis
        default_redis_provider: 127.0.0.1:6379
        pools:
            redis_pool:
                adapter: cache.adapter.redis
                public: true
                default_lifetime: 0
                provider: cache.default_redis_provider