# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
    form:
        legacy_error_messages: false
    http_client:
        scoped_clients:
            we_movie_api_client:
                base_uri: 'https://api.themoviedb.org/3/'
                auth_bearer: '%env(API_READ_ACCESS_TOKEN)%'
                headers:
                    Accept: 'application/json'

        default_options:
            max_redirects: 7
    secret: '%env(APP_SECRET)%'
    #csrf_protection: true
    http_method_override: false
    serializer:
        default_context:
            skip_null_values: true
        name_converter: 'serializer.name_converter.camel_case_to_snake_case'


    # Enables session support. Note that the session will ONLY be started if you read or write from it.
    # Remove or comment this section to explicitly disable session support.
    session:
        handler_id: null
        cookie_secure: auto
        cookie_samesite: lax
        storage_factory_id: session.storage.factory.native

    #esi: true
    #fragments: true
    php_errors:
        log: true

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
